from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class SignalAction(Enum):
    """Action type generated by a strategy signal."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass(frozen=True)
class Signal:
    """Immutable value object representing a single strategy signal.

    A signal is the pure output of a strategy's decision logic and contains
    no application-level configuration. It is intended to be consumed by
    execution/adapters that translate it into orders.
    """

    symbol: str
    action: SignalAction
    weight: float = 1.0
    score: float = 0.0
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not isinstance(self.symbol, str) or not self.symbol.strip():
            raise ValueError("symbol must be a non-empty string")
        if not isinstance(self.action, SignalAction):
            raise ValueError("action must be a SignalAction enum value")
        if not isinstance(self.weight, (int, float)):
            raise TypeError("weight must be a number")
        if not isinstance(self.score, (int, float)):
            raise TypeError("score must be a number")
        if not isinstance(self.reason, str):
            raise TypeError("reason must be a string")
        if not isinstance(self.metadata, dict):
            raise TypeError("metadata must be a dict")
